
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing: send all paths to index.html so React Router works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
